version: '3'
services:
  movie-web:
    build:
      context: ./movie-web
      dockerfile: Dockerfile
    ports:
    - "4000:4000"
  movie-gql:
    build:
      context: ./movie-gql
      dockerfile: Dockerfile
    ports:
    - "5000:5000"
volumes:
  dbvolume: {}