version: "3"
services:
  movie-web:
    build:
      context: ./movie-web
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
  movie-gql:
    build:
      context: ./movie-gql
      dockerfile: Dockerfile
    ports:
      - "4001:4001"
volumes:
  dbvolume: {}
