export default {
  data: {
    trending: {
      error: false,
      message: "",
      data: {
        page: 1,
        total_pages: 1000,
        total_results: 20000,
        results: [
          {
            id: 453395,
            poster_path: "/wRnbWt44nKjsFPrqSmwYki5vZtF.jpg",
            adult: false,
            overview:
              "Doctor Strange, with the help of mystical allies both old and new, traverses the mind-bending and dangerous alternate realities of the Multiverse to confront a mysterious new adversary.",
            release_date: "2022-05-04",
            genre_ids: [14, 28, 12],
            original_title: "Doctor Strange in the Multiverse of Madness",
            original_language: "en",
            title: "Doctor Strange in the Multiverse of Madness",
            backdrop_path: "/AdyJH8kDm8xT8IKTlgpEC15ny4u.jpg",
            popularity: 5007.839,
            vote_count: 1139,
            video: false,
            vote_average: 7.5,
            __typename: "TrendingResult",
          },
          {
            id: 414906,
            poster_path: "/74xTEgt7R36Fpooo50r9T25onhq.jpg",
            adult: false,
            overview:
              "In his second year of fighting crime, Batman uncovers corruption in Gotham City that connects to his own family while facing a serial killer known as the Riddler.",
            release_date: "2022-03-01",
            genre_ids: [80, 9648, 53],
            original_title: "The Batman",
            original_language: "en",
            title: "The Batman",
            backdrop_path: "/5P8SmMzSNYikXpxil6BYzJ16611.jpg",
            popularity: 4740.532,
            vote_count: 4401,
            video: false,
            vote_average: 7.8,
            __typename: "TrendingResult",
          },
          {
            id: 335787,
            poster_path: "/tlZpSxYuBRoVJBOpUrPdQe9FmFq.jpg",
            adult: false,
            overview:
              "A young street-smart, Nathan Drake and his wisecracking partner Victor “Sully” Sullivan embark on a dangerous pursuit of “the greatest treasure never found” while also tracking clues that may lead to Nathan’s long-lost brother.",
            release_date: "2022-02-10",
            genre_ids: [28, 12],
            original_title: "Uncharted",
            original_language: "en",
            title: "Uncharted",
            backdrop_path: "/aEGiJJP91HsKVTEPy1HhmN0wRLm.jpg",
            popularity: 4449.169,
            vote_count: 1796,
            video: false,
            vote_average: 7.2,
            __typename: "TrendingResult",
          },
          {
            id: 92749,
            poster_path: "/YksR65as1ppF2N48TJAh2PLamX.jpg",
            adult: null,
            overview:
              "When Steven Grant, a mild-mannered gift-shop employee, becomes plagued with blackouts and memories of another life, he discovers he has dissociative identity disorder and shares a body with mercenary Marc Spector. As Steven/Marc’s enemies converge upon them, they must navigate their complex identities while thrust into a deadly mystery among the powerful gods of Egypt.",
            release_date: null,
            genre_ids: [10759, 10765, 9648],
            original_title: null,
            original_language: "en",
            title: null,
            backdrop_path: "/1uegR4uAxRxiMyX4nQnpzbXhrTw.jpg",
            popularity: 4518.44,
            vote_count: 715,
            video: null,
            vote_average: 8.4,
            __typename: "TrendingResult",
          },
          {
            id: 675353,
            poster_path: "/6DrHO1jr3qVrViUO6s6kFiAGM7.jpg",
            adult: false,
            overview:
              "After settling in Green Hills, Sonic is eager to prove he has what it takes to be a true hero. His test comes when Dr. Robotnik returns, this time with a new partner, Knuckles, in search for an emerald that has the power to destroy civilizations. Sonic teams up with his own sidekick, Tails, and together they embark on a globe-trotting journey to find the emerald before it falls into the wrong hands.",
            release_date: "2022-03-30",
            genre_ids: [28, 878, 35, 10751, 12],
            original_title: "Sonic the Hedgehog 2",
            original_language: "en",
            title: "Sonic the Hedgehog 2",
            backdrop_path: "/egoyMDLqCxzjnSrWOz50uLlJWmD.jpg",
            popularity: 12851.144,
            vote_count: 1142,
            video: false,
            vote_average: 7.7,
            __typename: "TrendingResult",
          },
          {
            id: 829557,
            poster_path: "/7qU0SOVcQ8BTJLodcAlulUAG16C.jpg",
            adult: false,
            overview:
              "Laura and Massimo are back and hotter than ever. But the reunited couple's new beginning is complicated by Massimo’s family ties and a mysterious man who enters Laura’s life to win her heart and trust, at any cost.",
            release_date: "2022-04-27",
            genre_ids: [10749, 18],
            original_title: "365 Days: This Day",
            original_language: "pl",
            title: "365 Days: This Day",
            backdrop_path: "/t9hNIUFcy0tYu55IPxjxRTTdZ6X.jpg",
            popularity: 1823.374,
            vote_count: 346,
            video: false,
            vote_average: 5.7,
            __typename: "TrendingResult",
          },
          {
            id: 634649,
            poster_path: "/1g0dhYtq4irTY1GPXvft6k4YLjm.jpg",
            adult: false,
            overview:
              "Peter Parker is unmasked and no longer able to separate his normal life from the high-stakes of being a super-hero. When he asks for help from Doctor Strange the stakes become even more dangerous, forcing him to discover what it truly means to be Spider-Man.",
            release_date: "2021-12-15",
            genre_ids: [28, 12, 878],
            original_title: "Spider-Man: No Way Home",
            original_language: "en",
            title: "Spider-Man: No Way Home",
            backdrop_path: "/iQFcwSGbZXMkeyKrxbPnwnRo5fl.jpg",
            popularity: 3933.964,
            vote_count: 12602,
            video: false,
            vote_average: 8.1,
            __typename: "TrendingResult",
          },
          {
            id: 629542,
            poster_path: "/7qop80YfuO0BwJa1uXk1DXUUEwv.jpg",
            adult: false,
            overview:
              "When the infamous Bad Guys are finally caught after years of countless heists and being the world’s most-wanted villains, Mr. Wolf brokers a deal to save them all from prison.",
            release_date: "2022-03-17",
            genre_ids: [16, 35, 28, 10751, 80],
            original_title: "The Bad Guys",
            original_language: "en",
            title: "The Bad Guys",
            backdrop_path: "/fEe5fe82qHzjO4yej0o79etqsWV.jpg",
            popularity: 4730.107,
            vote_count: 305,
            video: false,
            vote_average: 7.7,
            __typename: "TrendingResult",
          },
          {
            id: 752623,
            poster_path: "/neMZH82Stu91d3iqvLdNQfqPPyl.jpg",
            adult: false,
            overview:
              "Follows a reclusive romance novelist who was sure nothing could be worse than getting stuck on a book tour with her cover model, until a kidnapping attempt sweeps them both into a cutthroat jungle adventure, proving life can be so much stranger, and more romantic, than any of her paperback fictions.",
            release_date: "2022-03-24",
            genre_ids: [12, 35, 10749],
            original_title: "The Lost City",
            original_language: "en",
            title: "The Lost City",
            backdrop_path: "/A3bsT0m1um6tvcmlIGxBwx9eAxn.jpg",
            popularity: 505.424,
            vote_count: 292,
            video: false,
            vote_average: 6.9,
            __typename: "TrendingResult",
          },
          {
            id: 763285,
            poster_path: "/kuxjMVuc3VTD7p42TZpJNsSrM1V.jpg",
            adult: false,
            overview:
              "Decorated veteran Will Sharp, desperate for money to cover his wife's medical bills, asks for help from his adoptive brother Danny. A charismatic career criminal, Danny instead offers him a score: the biggest bank heist in Los Angeles history: $32 million.",
            release_date: "2022-03-16",
            genre_ids: [28, 53, 80],
            original_title: "Ambulance",
            original_language: "en",
            title: "Ambulance",
            backdrop_path: "/192vHmAPbk5esL34XMKZ1YLGFjr.jpg",
            popularity: 2670.696,
            vote_count: 515,
            video: false,
            vote_average: 7,
            __typename: "TrendingResult",
          },
          {
            id: 52814,
            poster_path: "/nJUHX3XL1jMkk8honUZnUmudFb9.jpg",
            adult: null,
            overview:
              "Depicting an epic 26th-century conflict between humanity and an alien threat known as the Covenant, the series weaves deeply drawn personal stories with action, adventure and a richly imagined vision of the future.",
            release_date: null,
            genre_ids: [10759, 10765],
            original_title: null,
            original_language: "en",
            title: null,
            backdrop_path: "/1qpUk27LVI9UoTS7S0EixUBj5aR.jpg",
            popularity: 4451.565,
            vote_count: 590,
            video: null,
            vote_average: 8.7,
            __typename: "TrendingResult",
          },
          {
            id: 338953,
            poster_path: "/jrgifaYeUtTnaH7NF5Drkgjg2MB.jpg",
            adult: false,
            overview:
              "Professor Albus Dumbledore knows the powerful, dark wizard Gellert Grindelwald is moving to seize control of the wizarding world. Unable to stop him alone, he entrusts magizoologist Newt Scamander to lead an intrepid team of wizards and witches. They soon encounter an array of old and new beasts as they clash with Grindelwald's growing legion of followers.",
            release_date: "2022-04-06",
            genre_ids: [14, 12],
            original_title: "Fantastic Beasts: The Secrets of Dumbledore",
            original_language: "en",
            title: "Fantastic Beasts: The Secrets of Dumbledore",
            backdrop_path: "/wdjdHBDwmynWUrJcNzS24uegvK5.jpg",
            popularity: 826.325,
            vote_count: 920,
            video: false,
            vote_average: 6.8,
            __typename: "TrendingResult",
          },
          {
            id: 785985,
            poster_path: "/h5hVeCfYSb8gIO0F41gqidtb0AI.jpg",
            adult: false,
            overview:
              "Ousmane Diakité and François Monge are two cops with very different styles, backgrounds and careers. The unlikely pair are reunited once again for a new investigation that takes them across France. What seemed to be a simple drug deal turns out to be a much bigger criminal case wrapped in danger and unexpected comedy.",
            release_date: "2022-05-06",
            genre_ids: [35, 28],
            original_title: "Loin du périph",
            original_language: "fr",
            title: "The Takedown",
            backdrop_path: "/wtbRUVxQVvU6QIJH1oGLDThJLib.jpg",
            popularity: 182.687,
            vote_count: 68,
            video: false,
            vote_average: 5.7,
            __typename: "TrendingResult",
          },
          {
            id: 103516,
            poster_path: "/iwIdajr5Y4zq2ibvq75VnDAJBr.jpg",
            adult: null,
            overview:
              "Follow Christopher Pike, Spock and Number One in the years before Captain Kirk boarded the U.S.S. Enterprise, as they explore new worlds around the galaxy. sequel to the original series and discovery",
            release_date: null,
            genre_ids: [10765],
            original_title: null,
            original_language: "en",
            title: null,
            backdrop_path: "/rzAzvWJoZSwVSswvWsKx1lqT63m.jpg",
            popularity: 492.54,
            vote_count: 32,
            video: null,
            vote_average: 8,
            __typename: "TrendingResult",
          },
          {
            id: 406759,
            poster_path: "/odVv1sqVs0KxBXiA8bhIBlPgalx.jpg",
            adult: false,
            overview:
              "A mysterious force knocks the moon from its orbit around Earth and sends it hurtling on a collision course with life as we know it.",
            release_date: "2022-02-03",
            genre_ids: [878, 12, 28],
            original_title: "Moonfall",
            original_language: "en",
            title: "Moonfall",
            backdrop_path: "/x747ZvF0CcYYTTpPRCoUrxA2cYy.jpg",
            popularity: 2231.435,
            vote_count: 935,
            video: false,
            vote_average: 6.5,
            __typename: "TrendingResult",
          },
          {
            id: 60059,
            poster_path: "/fC2HDm5t0kHl7mTm7jxMR31b7by.jpg",
            adult: null,
            overview:
              'Six years before Saul Goodman meets Walter White. We meet him when the man who will become Saul Goodman is known as Jimmy McGill, a small-time lawyer searching for his destiny, and, more immediately, hustling to make ends meet. Working alongside, and, often, against Jimmy, is “fixer” Mike Ehrmantraut. The series tracks Jimmy’s transformation into Saul Goodman, the man who puts “criminal” in “criminal lawyer".',
            release_date: null,
            genre_ids: [35, 80, 18],
            original_title: null,
            original_language: "en",
            title: null,
            backdrop_path: "/t15KHp3iNfHVQBNIaqUGW12xQA4.jpg",
            popularity: 331.261,
            vote_count: 2709,
            video: null,
            vote_average: 8.5,
            __typename: "TrendingResult",
          },
          {
            id: 508947,
            poster_path: "/qsdjk9oAKSQMWs0Vt5Pyfh6O4GZ.jpg",
            adult: false,
            overview:
              "Thirteen-year-old Mei is experiencing the awkwardness of being a teenager with a twist – when she gets too excited, she transforms into a giant red panda.",
            release_date: "2022-03-10",
            genre_ids: [16, 10751, 35, 14],
            original_title: "Turning Red",
            original_language: "en",
            title: "Turning Red",
            backdrop_path: "/fOy2Jurz9k6RnJnMUMRDAgBwru2.jpg",
            popularity: 2493.062,
            vote_count: 2058,
            video: false,
            vote_average: 7.4,
            __typename: "TrendingResult",
          },
          {
            id: 664413,
            poster_path: "/6KwrHucIE3CvNT7kTm2MAlZ4fYF.jpg",
            adult: false,
            overview:
              "A woman falls victim to a dominant mafia boss, who imprisons her and gives her one year to fall in love with him.",
            release_date: "2020-02-07",
            genre_ids: [10749, 18],
            original_title: "365 dni",
            original_language: "pl",
            title: "365 Days",
            backdrop_path: "/isBjNHBblzxrzHrAtRbjgkYzAut.jpg",
            popularity: 100.791,
            vote_count: 6826,
            video: false,
            vote_average: 7,
            __typename: "TrendingResult",
          },
          {
            id: 505026,
            poster_path: "/kVr5zIAFSPRQ57Y1zE7KzmhzdMQ.jpg",
            adult: false,
            overview:
              "Belgian sleuth Hercule Poirot boards a glamorous river steamer with enough champagne to fill the Nile. But his Egyptian vacation turns into a thrilling search for a murderer when a picture-perfect couple’s idyllic honeymoon is tragically cut short.",
            release_date: "2022-02-09",
            genre_ids: [80, 18, 9648, 53],
            original_title: "Death on the Nile",
            original_language: "en",
            title: "Death on the Nile",
            backdrop_path: "/lRbDyjI7HEaXxflFQbYpqHRGFBJ.jpg",
            popularity: 256.853,
            vote_count: 1602,
            video: false,
            vote_average: 6.5,
            __typename: "TrendingResult",
          },
          {
            id: 113985,
            poster_path: "/nO2qkja0cYBlx59fJ89TnrzDvHe.jpg",
            adult: null,
            overview:
              "A rancher fighting for his land and family stumbles upon an unfathomable mystery at the edge of Wyoming’s wilderness, forcing a confrontation with the Unknown in ways both intimate and cosmic in the untamable American West.",
            release_date: null,
            genre_ids: [37, 9648],
            original_title: null,
            original_language: "en",
            title: null,
            backdrop_path: "/wI4aGtreUx7vFtZGcyiFoOX3qf3.jpg",
            popularity: 66.164,
            vote_count: 43,
            video: null,
            vote_average: 6.9,
            __typename: "TrendingResult",
          },
        ],
        __typename: "TrendingData",
      },
      __typename: "TrendingList",
    },
  },
};
